spring:
  application:
    name: gateway-server

  cloud:
    config:
      uri: http://localhost:8071

  config:
    import: configserver:http://localhost:8071

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 8095
