
services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8997:8997"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CLOUD_CONFIG_URI: http://localhost:8071"


    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge
