spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
  config:
    import: configserver:http://localhost:8071


  resilience4j:
    circuitbreaker:
      instances:
        licenseService:
          registerHealthIndicator: true
          eventConsumerBufferSize: 5
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          slidingWindowType: COUNT_BASED
          recordExceptions:
            - org.springframework.web.client.HttpServerErrorException
            - java.io.IOException- java.util.concurrent.TimeoutException
            - org.springframework.web.client.ResourceAccessException


