spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://configserver:8079
  config:
    import: configserver:http://configserver:8079


  resilience4j:
    circuitbreaker:
      instances:
        licenseService:
          registerHealthIndicator: true
          eventConsumerBufferSize: 5
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          slidingWindowType: COUNT_BASED
          recordExceptions:
            - org.springframework.web.client.HttpServerErrorException
            - java.io.IOException- java.util.concurrent.TimeoutException
            - org.springframework.web.client.ResourceAccessException
    bulkhead:
      instances:
        bulkheadLicenseService:
          maxWaitDuration: 10ms
          maxConcurrentCalls: 20

    thread-pool-bulkhead:
      instances:
        bulkheadLicenseService:
          maxThreadPoolSize: 1
          coreThreadPoolSize: 1
          queueCapacity: 1
          keepAliveDuration: 20ms

    retry:
      instance:
        retryLicenseService:
          maxRetryAttempts: 5
          waitDuration: 10000
          retry-exceptions:
            - java.util.concurrent.TimeoutException




