spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tadiewa/licensing_configs

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Include gateway endpoints for actuator
  endpoint:
    gateway:
      enabled: true  # Ensure gateway actuator endpoints are enabled
