spring:
  application:
    name: config-server

  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tadiewa/licensing_configs

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/




server:
  port: 8071