spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8071
  config:
    import: configserver:http://localhost:8071

  loadbalancer:
    ribbon:
      enabled: false
