spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8079
  config:
    import: configserver:http://localhost:8079

  loadbalancer:
    ribbon:
      enabled: false


